oss:
  minio:
    endpoint: "localhost:9000"
    upload_host: "localhost:9000"
    download_host: "http://localhost:9000"
    access_key: "root"
    secret_key: "*Abcd123456"
    token: ""
    use_ssl: false
